project:
  type: website
  output-dir: docs
website:
  title: "LSHTM - ASME"
  search: 
    type: overlay
  sidebar: 
    id: home
    style: "docked"
    contents: 
      - ASME_02.qmd
      - ASME_04.qmd
      - ASME_06.qmd
      - ASME_07.qmd
      - ASME_08.qmd
      - ASME_09.qmd
      - ASME_10.qmd
      - ASME_11.qmd
      - ASME_12.qmd
      - ASME_15.qmd
      - ASME_16.qmd
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - review.qmd

format:
  html:
    theme: cosmo
    code-copy: hover
    css: styles.css
    toc: true

editor: visual

